"""
agentnotary.compliance.renderers.markdown
======================================
Render the abstract document tree as committable, diff-friendly Markdown.
"""

from __future__ import annotations


def render(doc: dict, *, disclaimer: str) -> str:
    out = []

    # Header
    out.append(f"# {doc['title']}")
    out.append(f"**{doc['subtitle']}** | Generated: `{doc['generated_at']}`")
    if doc.get("seal_hash"):
        out.append(f" | Seal: `{doc['seal_hash'][:24]}...`")
    out.append("")
    out.append(f"**Risk class:** `{doc['risk_class'].upper()}`")
    out.append("")

    # Disclaimer banner
    out.append("> ⚠️  **Important Notice**")
    out.append(f"> {disclaimer}")
    out.append("")
    out.append("---")
    out.append("")

    # Table of contents
    out.append("## Contents")
    for s in doc["sections"]:
        out.append(f"- [{s['id']}. {s['heading']}](#{_anchor(s['id'], s['heading'])})")
    out.append("")
    out.append("---")
    out.append("")

    # Sections
    for s in doc["sections"]:
        out.append(f"## {s['id']}. {s['heading']}")
        out.append("")
        if "fields" in s:
            for label, value in s["fields"]:
                out.append(f"- **{label}:** {value}")
            out.append("")
        if "body" in s:
            out.append(s["body"])
            out.append("")
        if "subsections" in s:
            for sub in s["subsections"]:
                out.append(f"### {sub['heading']}")
                out.append("")
                if "fields" in sub:
                    for label, value in sub["fields"]:
                        out.append(f"- **{label}:** {value}")
                    out.append("")
                if "body" in sub:
                    out.append(sub["body"])
                    out.append("")

    out.append("---")
    out.append("")
    out.append("_Generated by [AgentNotary](https://github.com/CharanBharathula/agentnotary) "
               "`agentnotary compliance`._")
    out.append("")

    return "\n".join(out)


def _anchor(section_id: str, heading: str) -> str:
    return f"{section_id}-" + heading.lower().replace(" ", "-").replace(",", "")
